# Generated by Django 2.1.5 on 2019-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserToken',
            fields=[
                ('user_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
                ('token', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'auth_tokens',
                'managed': False,
            },
        ),
    ]
